server.port: 8443
spring:
  cloud:
    gateway.server.webflux.routes:
      - id: path_route
        uri: lb://course-composite-service
        predicates:
          - Path=/api/v1/**
        filters:
          - name: CircuitBreaker
            args:
              name: course-composite-circuit-breaker
              fallbackUri: forward:/fallback
      - id: eureka-web-start
        uri: http://${app.eureka-service}:8761
        predicates:
          - Path=/eureka/web
        filters:
          - SetPath=/
      - id: eureka-web-other
        uri: http://${app.eureka-service}:8761
        predicates:
          - Path=/eureka/**
app.eureka-service: discovery
app.course-composite-service: course-composite-service