spring.config.activate.on-profile: test
server.port: 8080
logging:
  level:
    org:
      springframework:
        amqp: debug
        cloud: debug
spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres
  rabbitmq:
    host: rabbitmq
eureka.client.service-url.defaultZone: http://discovery:8761/eureka/