spring.config.activate.on-profile: dev
server.port: 8080
logging:
  level:
    org:
      springframework:
        amqp: debug
        cloud: debug
spring:
  r2dbc:
    url: r2dbc:postgresql://postgresql:5432/postgres
    username: postgres
    password: postgres
  rabbitmq:
    host: rabbitmq
eureka.client.service-url.defaultZone: http://discovery:8761/eureka/