
logging:
  level:
    org:
      springframework:
        amqp: debug
        cloud: debug
spring:
  r2dbc:
    url: r2dbc:postgresql://postgresql:5432/postgres
    username: postgres
    password: postgres
  rabbitmq:
    host: rabbitmq